/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as PerfectRouteImport } from './routes/perfect'
import { Route as OccurrencesRouteImport } from './routes/occurrences'
import { Route as HeadcountRouteImport } from './routes/headcount'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfectRoute = PerfectRouteImport.update({
  id: '/perfect',
  path: '/perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const OccurrencesRoute = OccurrencesRouteImport.update({
  id: '/occurrences',
  path: '/occurrences',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadcountRoute = HeadcountRouteImport.update({
  id: '/headcount',
  path: '/headcount',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coverage': typeof CoverageRoute
  '/headcount': typeof HeadcountRoute
  '/occurrences': typeof OccurrencesRoute
  '/perfect': typeof PerfectRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coverage': typeof CoverageRoute
  '/headcount': typeof HeadcountRoute
  '/occurrences': typeof OccurrencesRoute
  '/perfect': typeof PerfectRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coverage': typeof CoverageRoute
  '/headcount': typeof HeadcountRoute
  '/occurrences': typeof OccurrencesRoute
  '/perfect': typeof PerfectRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/coverage'
    | '/headcount'
    | '/occurrences'
    | '/perfect'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/coverage'
    | '/headcount'
    | '/occurrences'
    | '/perfect'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/coverage'
    | '/headcount'
    | '/occurrences'
    | '/perfect'
    | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CoverageRoute: typeof CoverageRoute
  HeadcountRoute: typeof HeadcountRoute
  OccurrencesRoute: typeof OccurrencesRoute
  PerfectRoute: typeof PerfectRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfect': {
      id: '/perfect'
      path: '/perfect'
      fullPath: '/perfect'
      preLoaderRoute: typeof PerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occurrences': {
      id: '/occurrences'
      path: '/occurrences'
      fullPath: '/occurrences'
      preLoaderRoute: typeof OccurrencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headcount': {
      id: '/headcount'
      path: '/headcount'
      fullPath: '/headcount'
      preLoaderRoute: typeof HeadcountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CoverageRoute: CoverageRoute,
  HeadcountRoute: HeadcountRoute,
  OccurrencesRoute: OccurrencesRoute,
  PerfectRoute: PerfectRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
